apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: devops-apps
  labels:
    app: auth 
spec:
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
