apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: viviennedofit-ingress
  namespace: devops-apps  # Match your target namespace
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health  # Adjust if needed
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: viviennedofit.com
    http:
      paths:
      - path: /auth*  # ALB uses * for prefix matching
        pathType: Prefix
        backend:
          service:
            name: auth
            port:
              number: 3000
      - path: /products*
        pathType: Prefix
        backend:
          service:
            name: products
            port:
              number: 3001
      - path: /orders*
        pathType: Prefix
        backend:
          service:
            name: orders
            port:
              number: 3002
  tls:
  - hosts:
    - viviennedofit.com
    secretName: viviennedofit-tls



