# # svc-monitor-auth.yaml
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: auth-monitor
#   namespace: monitoring
#   labels:
#     release: prometheus
# spec:
#   selector:
#     matchLabels:
#       app: auth
#   namespaceSelector:
#     matchNames:
#     - devops-apps
#   endpoints:
#   - port: http
#     path: /metrics
#     interval: 15s

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-monitor
  namespace: monitoring  # Keep in monitoring namespace if Prometheus operates there
  labels:
    release: prometheus  # This must match your Prometheus' serviceMonitorSelector
spec:
  jobLabel: app          # Creates more descriptive job labels
  selector:
    matchLabels:
      app: auth          # Matches your Service's labels
  namespaceSelector:
    matchNames:
    - devops-apps        # Where your auth Service lives
  endpoints:
  - port: http           # Must match the Service's port name
    path: /metrics
    interval: 15s
    honorLabels: true    # Preserve original labels