apiVersion: v1
kind: Service
metadata:
  name: products
  namespace: devops-apps
  labels:
    app: products  
spec:
  selector:
    app: products
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
