apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: devops-apps
  labels:
    app: orders  
spec:
  selector:
    app: orders
  ports:
    - name: http
      # This port name should match the one used in the ServiceMonitor
      # to ensure proper scraping by Prometheus.
      protocol: TCP
      port: 80
      targetPort: 3002
